/*
 * Worker API and Events
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EmploymentDetails
 */
public class EmploymentDetailsTest {
    private final EmploymentDetails model = new EmploymentDetails();

    /**
     * Model tests for EmploymentDetails
     */
    @Test
    public void testEmploymentDetails() {
        // TODO: test EmploymentDetails
    }

    /**
     * Test the property 'employmentStatus'
     */
    @Test
    public void employmentStatusTest() {
        // TODO: test employmentStatus
    }

    /**
     * Test the property 'employeeType'
     */
    @Test
    public void employeeTypeTest() {
        // TODO: test employeeType
    }

    /**
     * Test the property 'hireDetails'
     */
    @Test
    public void hireDetailsTest() {
        // TODO: test hireDetails
    }

    /**
     * Test the property 'dateJoinedNHS'
     */
    @Test
    public void dateJoinedNHSTest() {
        // TODO: test dateJoinedNHS
    }

    /**
     * Test the property 'alAccrualPlan'
     */
    @Test
    public void alAccrualPlanTest() {
        // TODO: test alAccrualPlan
    }

    /**
     * Test the property 'prevEmployer'
     */
    @Test
    public void prevEmployerTest() {
        // TODO: test prevEmployer
    }

    /**
     * Test the property 'agencies'
     */
    @Test
    public void agenciesTest() {
        // TODO: test agencies
    }

}
