/* 
 * Duty Booking API and Events
 *
 * ## Duty Booking API and events and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing DutyDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DutyDetailsTests
    {
        // TODO uncomment below to declare an instance variable for DutyDetails
        //private DutyDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DutyDetails
            //instance = new DutyDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DutyDetails
        /// </summary>
        [Test]
        public void DutyDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DutyDetails
            //Assert.IsInstanceOf(typeof(DutyDetails), instance);
        }


        /// <summary>
        /// Test the property 'When'
        /// </summary>
        [Test]
        public void WhenTest()
        {
            // TODO unit test for the property 'When'
        }
        /// <summary>
        /// Test the property 'Where'
        /// </summary>
        [Test]
        public void WhereTest()
        {
            // TODO unit test for the property 'Where'
        }
        /// <summary>
        /// Test the property 'Requirements'
        /// </summary>
        [Test]
        public void RequirementsTest()
        {
            // TODO unit test for the property 'Requirements'
        }

    }

}
