/* 
 * Duty Booking API and Events
 *
 * ## Duty Booking API and events and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing DutyRequirementsGradeRequirement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DutyRequirementsGradeRequirementTests
    {
        // TODO uncomment below to declare an instance variable for DutyRequirementsGradeRequirement
        //private DutyRequirementsGradeRequirement instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DutyRequirementsGradeRequirement
            //instance = new DutyRequirementsGradeRequirement();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DutyRequirementsGradeRequirement
        /// </summary>
        [Test]
        public void DutyRequirementsGradeRequirementInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DutyRequirementsGradeRequirement
            //Assert.IsInstanceOf(typeof(DutyRequirementsGradeRequirement), instance);
        }


        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'GradeType'
        /// </summary>
        [Test]
        public void GradeTypeTest()
        {
            // TODO unit test for the property 'GradeType'
        }
        /// <summary>
        /// Test the property 'GradeTypeCategory'
        /// </summary>
        [Test]
        public void GradeTypeCategoryTest()
        {
            // TODO unit test for the property 'GradeTypeCategory'
        }

    }

}
