/* 
 * Workers
 *
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing AvailabilitiesAvailability
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilitiesAvailabilityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailabilitiesAvailability
        //private AvailabilitiesAvailability instance;

        public AvailabilitiesAvailabilityTests()
        {
            // TODO uncomment below to create an instance of AvailabilitiesAvailability
            //instance = new AvailabilitiesAvailability();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailabilitiesAvailability
        /// </summary>
        [Fact]
        public void AvailabilitiesAvailabilityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AvailabilitiesAvailability
            //Assert.IsInstanceOfType<AvailabilitiesAvailability> (instance, "variable 'instance' is a AvailabilitiesAvailability");
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'AvailabilityType'
        /// </summary>
        [Fact]
        public void AvailabilityTypeTest()
        {
            // TODO unit test for the property 'AvailabilityType'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'NumberOfOccurrences'
        /// </summary>
        [Fact]
        public void NumberOfOccurrencesTest()
        {
            // TODO unit test for the property 'NumberOfOccurrences'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }

    }

}
