/*
 * Workers
 *
 * ## Workers and events 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

type Skill struct {

	SkillGroup string `json:"skillGroup,omitempty"`

	Cluster string `json:"cluster,omitempty"`

	Skill string `json:"skill,omitempty"`

	Validity DateSpan `json:"validity"`

	DateGained string `json:"dateGained,omitempty"`

	ObtainedFromReason string `json:"obtainedFromReason,omitempty"`

	CertificateNumber string `json:"certificateNumber,omitempty"`

	Notes string `json:"notes,omitempty"`
}
