# coding: utf-8

"""
    Worker API and Events

         ## API and events for providing workers.   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from api_server.configuration import Configuration


class PersonalPattern(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'duty': 'list[object]',
        'unavailability': 'list[object]'
    }

    attribute_map = {
        'duty': 'duty',
        'unavailability': 'unavailability'
    }

    def __init__(self, duty=None, unavailability=None, local_vars_configuration=None):  # noqa: E501
        """PersonalPattern - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._duty = None
        self._unavailability = None
        self.discriminator = None

        if duty is not None:
            self.duty = duty
        if unavailability is not None:
            self.unavailability = unavailability

    @property
    def duty(self):
        """Gets the duty of this PersonalPattern.  # noqa: E501


        :return: The duty of this PersonalPattern.  # noqa: E501
        :rtype: list[object]
        """
        return self._duty

    @duty.setter
    def duty(self, duty):
        """Sets the duty of this PersonalPattern.


        :param duty: The duty of this PersonalPattern.  # noqa: E501
        :type: list[object]
        """

        self._duty = duty

    @property
    def unavailability(self):
        """Gets the unavailability of this PersonalPattern.  # noqa: E501


        :return: The unavailability of this PersonalPattern.  # noqa: E501
        :rtype: list[object]
        """
        return self._unavailability

    @unavailability.setter
    def unavailability(self, unavailability):
        """Sets the unavailability of this PersonalPattern.


        :param unavailability: The unavailability of this PersonalPattern.  # noqa: E501
        :type: list[object]
        """

        self._unavailability = unavailability

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonalPattern):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PersonalPattern):
            return True

        return self.to_dict() != other.to_dict()
