/**
 * Worker API and Events
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Contract { 
    staffGroup?: string;
    grade: string;
    contract: string;
    payscale?: string;
    contractType?: string;
    contractedTime: string;
    defaultUnavailabilityHours?: string;
    wtdOptOut?: boolean;
    salaryFrequency?: string;
    salaryAmount?: number;
}

