/**
 * Worker API and Events
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject { 
    /**
     * The code for the trust that the worker should be on-boarded to
     */
    trustCode?: string;
    /**
     * The \'engagement route\' of the worker, such as substantive, bank, agency
     */
    engagementRoute?: string;
}

