/*
 * VMS Provisioning API
 *
 * ## Description  API to be impemented by 247Time (and, potentially, partners) to enable provisioning of accounts and the org structure 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

type Unit struct {

	Id string `json:"id"`

	Name string `json:"name"`

	CostCentre CostCentre `json:"costCentre,omitempty"`

	StaffGroups []StaffGroup `json:"staffGroups,omitempty"`

	// Children of this unit. This may be an arbitarily deep tree structure.
	Children []Unit `json:"children,omitempty"`
}
