# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_server.models.base_model_ import Model
from api_server import util


class DutyRequirements(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, skill=None, specialty=None, fallback_skill=None, fallback_speciality=None):  # noqa: E501
        """DutyRequirements - a model defined in OpenAPI

        :param skill: The skill of this DutyRequirements.  # noqa: E501
        :type skill: str
        :param specialty: The specialty of this DutyRequirements.  # noqa: E501
        :type specialty: str
        :param fallback_skill: The fallback_skill of this DutyRequirements.  # noqa: E501
        :type fallback_skill: str
        :param fallback_speciality: The fallback_speciality of this DutyRequirements.  # noqa: E501
        :type fallback_speciality: str
        """
        self.openapi_types = {
            'skill': str,
            'specialty': str,
            'fallback_skill': str,
            'fallback_speciality': str
        }

        self.attribute_map = {
            'skill': 'skill',
            'specialty': 'specialty',
            'fallback_skill': 'fallbackSkill',
            'fallback_speciality': 'fallbackSpeciality'
        }

        self._skill = skill
        self._specialty = specialty
        self._fallback_skill = fallback_skill
        self._fallback_speciality = fallback_speciality

    @classmethod
    def from_dict(cls, dikt) -> 'DutyRequirements':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DutyRequirements of this DutyRequirements.  # noqa: E501
        :rtype: DutyRequirements
        """
        return util.deserialize_model(dikt, cls)

    @property
    def skill(self):
        """Gets the skill of this DutyRequirements.

        Text description  # noqa: E501

        :return: The skill of this DutyRequirements.
        :rtype: str
        """
        return self._skill

    @skill.setter
    def skill(self, skill):
        """Sets the skill of this DutyRequirements.

        Text description  # noqa: E501

        :param skill: The skill of this DutyRequirements.
        :type skill: str
        """

        self._skill = skill

    @property
    def specialty(self):
        """Gets the specialty of this DutyRequirements.

        Text description  # noqa: E501

        :return: The specialty of this DutyRequirements.
        :rtype: str
        """
        return self._specialty

    @specialty.setter
    def specialty(self, specialty):
        """Sets the specialty of this DutyRequirements.

        Text description  # noqa: E501

        :param specialty: The specialty of this DutyRequirements.
        :type specialty: str
        """

        self._specialty = specialty

    @property
    def fallback_skill(self):
        """Gets the fallback_skill of this DutyRequirements.

        Text description  # noqa: E501

        :return: The fallback_skill of this DutyRequirements.
        :rtype: str
        """
        return self._fallback_skill

    @fallback_skill.setter
    def fallback_skill(self, fallback_skill):
        """Sets the fallback_skill of this DutyRequirements.

        Text description  # noqa: E501

        :param fallback_skill: The fallback_skill of this DutyRequirements.
        :type fallback_skill: str
        """

        self._fallback_skill = fallback_skill

    @property
    def fallback_speciality(self):
        """Gets the fallback_speciality of this DutyRequirements.

        Text description  # noqa: E501

        :return: The fallback_speciality of this DutyRequirements.
        :rtype: str
        """
        return self._fallback_speciality

    @fallback_speciality.setter
    def fallback_speciality(self, fallback_speciality):
        """Sets the fallback_speciality of this DutyRequirements.

        Text description  # noqa: E501

        :param fallback_speciality: The fallback_speciality of this DutyRequirements.
        :type fallback_speciality: str
        """

        self._fallback_speciality = fallback_speciality
