# coding: utf-8

"""
    VMS API

    ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api_server
from api_server.models.worker_offer import WorkerOffer  # noqa: E501
from api_server.rest import ApiException


class TestWorkerOffer(unittest.TestCase):
    """WorkerOffer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkerOffer(self):
        """Test WorkerOffer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api_server.models.worker_offer.WorkerOffer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
