# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_server.models.base_model_ import Model
from api_server import util


class WorkingRestrictionDefaultLeaveHours(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, use_working_day=None, monday_time=None, tuesday_time=None, wednesday_time=None, friday_time=None, saturday_time=None, sunday_time=None):  # noqa: E501
        """WorkingRestrictionDefaultLeaveHours - a model defined in OpenAPI

        :param use_working_day: The use_working_day of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type use_working_day: str
        :param monday_time: The monday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type monday_time: str
        :param tuesday_time: The tuesday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type tuesday_time: str
        :param wednesday_time: The wednesday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type wednesday_time: str
        :param friday_time: The friday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type friday_time: str
        :param saturday_time: The saturday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type saturday_time: str
        :param sunday_time: The sunday_time of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :type sunday_time: str
        """
        self.openapi_types = {
            'use_working_day': str,
            'monday_time': str,
            'tuesday_time': str,
            'wednesday_time': str,
            'friday_time': str,
            'saturday_time': str,
            'sunday_time': str
        }

        self.attribute_map = {
            'use_working_day': 'useWorkingDay',
            'monday_time': 'mondayTime',
            'tuesday_time': 'tuesdayTime',
            'wednesday_time': 'wednesdayTime',
            'friday_time': 'fridayTime',
            'saturday_time': 'saturdayTime',
            'sunday_time': 'sundayTime'
        }

        self._use_working_day = use_working_day
        self._monday_time = monday_time
        self._tuesday_time = tuesday_time
        self._wednesday_time = wednesday_time
        self._friday_time = friday_time
        self._saturday_time = saturday_time
        self._sunday_time = sunday_time

    @classmethod
    def from_dict(cls, dikt) -> 'WorkingRestrictionDefaultLeaveHours':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The WorkingRestriction_defaultLeaveHours of this WorkingRestrictionDefaultLeaveHours.  # noqa: E501
        :rtype: WorkingRestrictionDefaultLeaveHours
        """
        return util.deserialize_model(dikt, cls)

    @property
    def use_working_day(self):
        """Gets the use_working_day of this WorkingRestrictionDefaultLeaveHours.


        :return: The use_working_day of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._use_working_day

    @use_working_day.setter
    def use_working_day(self, use_working_day):
        """Sets the use_working_day of this WorkingRestrictionDefaultLeaveHours.


        :param use_working_day: The use_working_day of this WorkingRestrictionDefaultLeaveHours.
        :type use_working_day: str
        """

        self._use_working_day = use_working_day

    @property
    def monday_time(self):
        """Gets the monday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The monday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._monday_time

    @monday_time.setter
    def monday_time(self, monday_time):
        """Sets the monday_time of this WorkingRestrictionDefaultLeaveHours.


        :param monday_time: The monday_time of this WorkingRestrictionDefaultLeaveHours.
        :type monday_time: str
        """

        self._monday_time = monday_time

    @property
    def tuesday_time(self):
        """Gets the tuesday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The tuesday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._tuesday_time

    @tuesday_time.setter
    def tuesday_time(self, tuesday_time):
        """Sets the tuesday_time of this WorkingRestrictionDefaultLeaveHours.


        :param tuesday_time: The tuesday_time of this WorkingRestrictionDefaultLeaveHours.
        :type tuesday_time: str
        """

        self._tuesday_time = tuesday_time

    @property
    def wednesday_time(self):
        """Gets the wednesday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The wednesday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._wednesday_time

    @wednesday_time.setter
    def wednesday_time(self, wednesday_time):
        """Sets the wednesday_time of this WorkingRestrictionDefaultLeaveHours.


        :param wednesday_time: The wednesday_time of this WorkingRestrictionDefaultLeaveHours.
        :type wednesday_time: str
        """

        self._wednesday_time = wednesday_time

    @property
    def friday_time(self):
        """Gets the friday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The friday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._friday_time

    @friday_time.setter
    def friday_time(self, friday_time):
        """Sets the friday_time of this WorkingRestrictionDefaultLeaveHours.


        :param friday_time: The friday_time of this WorkingRestrictionDefaultLeaveHours.
        :type friday_time: str
        """

        self._friday_time = friday_time

    @property
    def saturday_time(self):
        """Gets the saturday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The saturday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._saturday_time

    @saturday_time.setter
    def saturday_time(self, saturday_time):
        """Sets the saturday_time of this WorkingRestrictionDefaultLeaveHours.


        :param saturday_time: The saturday_time of this WorkingRestrictionDefaultLeaveHours.
        :type saturday_time: str
        """

        self._saturday_time = saturday_time

    @property
    def sunday_time(self):
        """Gets the sunday_time of this WorkingRestrictionDefaultLeaveHours.


        :return: The sunday_time of this WorkingRestrictionDefaultLeaveHours.
        :rtype: str
        """
        return self._sunday_time

    @sunday_time.setter
    def sunday_time(self, sunday_time):
        """Sets the sunday_time of this WorkingRestrictionDefaultLeaveHours.


        :param sunday_time: The sunday_time of this WorkingRestrictionDefaultLeaveHours.
        :type sunday_time: str
        """

        self._sunday_time = sunday_time
