/*
 * VMS API
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.vms.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * BookingCancelledEvent
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T13:35:13.806839Z[Europe/London]")
public class BookingCancelledEvent {
  public static final String SERIALIZED_NAME_BOOKING_REQUEST_ID = "bookingRequestId";
  @SerializedName(SERIALIZED_NAME_BOOKING_REQUEST_ID)
  private String bookingRequestId;

  public static final String SERIALIZED_NAME_BOOKING_ID = "bookingId";
  @SerializedName(SERIALIZED_NAME_BOOKING_ID)
  private String bookingId;

  public static final String SERIALIZED_NAME_AGENCY_ID = "agencyId";
  @SerializedName(SERIALIZED_NAME_AGENCY_ID)
  private String agencyId;

  public static final String SERIALIZED_NAME_COST = "cost";
  @SerializedName(SERIALIZED_NAME_COST)
  private BigDecimal cost;


  public BookingCancelledEvent bookingRequestId(String bookingRequestId) {
    
    this.bookingRequestId = bookingRequestId;
    return this;
  }

   /**
   * Get bookingRequestId
   * @return bookingRequestId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBookingRequestId() {
    return bookingRequestId;
  }


  public void setBookingRequestId(String bookingRequestId) {
    this.bookingRequestId = bookingRequestId;
  }


  public BookingCancelledEvent bookingId(String bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

   /**
   * Get bookingId
   * @return bookingId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getBookingId() {
    return bookingId;
  }


  public void setBookingId(String bookingId) {
    this.bookingId = bookingId;
  }


  public BookingCancelledEvent agencyId(String agencyId) {
    
    this.agencyId = agencyId;
    return this;
  }

   /**
   * Get agencyId
   * @return agencyId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAgencyId() {
    return agencyId;
  }


  public void setAgencyId(String agencyId) {
    this.agencyId = agencyId;
  }


  public BookingCancelledEvent cost(BigDecimal cost) {
    
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "123.45", value = "")

  public BigDecimal getCost() {
    return cost;
  }


  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookingCancelledEvent bookingCancelledEvent = (BookingCancelledEvent) o;
    return Objects.equals(this.bookingRequestId, bookingCancelledEvent.bookingRequestId) &&
        Objects.equals(this.bookingId, bookingCancelledEvent.bookingId) &&
        Objects.equals(this.agencyId, bookingCancelledEvent.agencyId) &&
        Objects.equals(this.cost, bookingCancelledEvent.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingRequestId, bookingId, agencyId, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookingCancelledEvent {\n");
    sb.append("    bookingRequestId: ").append(toIndentedString(bookingRequestId)).append("\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    agencyId: ").append(toIndentedString(agencyId)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

