/*
 * Worker API and Events
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Contract
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T13:34:21.101948Z[Europe/London]")
public class Contract {
  public static final String SERIALIZED_NAME_STAFF_GROUP = "staffGroup";
  @SerializedName(SERIALIZED_NAME_STAFF_GROUP)
  private String staffGroup;

  public static final String SERIALIZED_NAME_GRADE = "grade";
  @SerializedName(SERIALIZED_NAME_GRADE)
  private String grade;

  public static final String SERIALIZED_NAME_CONTRACT = "contract";
  @SerializedName(SERIALIZED_NAME_CONTRACT)
  private String contract;

  public static final String SERIALIZED_NAME_PAYSCALE = "payscale";
  @SerializedName(SERIALIZED_NAME_PAYSCALE)
  private String payscale;

  public static final String SERIALIZED_NAME_CONTRACT_TYPE = "contractType";
  @SerializedName(SERIALIZED_NAME_CONTRACT_TYPE)
  private String contractType;

  public static final String SERIALIZED_NAME_CONTRACTED_TIME = "contractedTime";
  @SerializedName(SERIALIZED_NAME_CONTRACTED_TIME)
  private String contractedTime;

  public static final String SERIALIZED_NAME_DEFAULT_UNAVAILABILITY_HOURS = "defaultUnavailabilityHours";
  @SerializedName(SERIALIZED_NAME_DEFAULT_UNAVAILABILITY_HOURS)
  private String defaultUnavailabilityHours;

  public static final String SERIALIZED_NAME_WTD_OPT_OUT = "wtdOptOut";
  @SerializedName(SERIALIZED_NAME_WTD_OPT_OUT)
  private Boolean wtdOptOut;

  public static final String SERIALIZED_NAME_SALARY_FREQUENCY = "salaryFrequency";
  @SerializedName(SERIALIZED_NAME_SALARY_FREQUENCY)
  private String salaryFrequency;

  public static final String SERIALIZED_NAME_SALARY_AMOUNT = "salaryAmount";
  @SerializedName(SERIALIZED_NAME_SALARY_AMOUNT)
  private BigDecimal salaryAmount;


  public Contract staffGroup(String staffGroup) {
    
    this.staffGroup = staffGroup;
    return this;
  }

   /**
   * Get staffGroup
   * @return staffGroup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStaffGroup() {
    return staffGroup;
  }


  public void setStaffGroup(String staffGroup) {
    this.staffGroup = staffGroup;
  }


  public Contract grade(String grade) {
    
    this.grade = grade;
    return this;
  }

   /**
   * Get grade
   * @return grade
  **/
  @ApiModelProperty(required = true, value = "")

  public String getGrade() {
    return grade;
  }


  public void setGrade(String grade) {
    this.grade = grade;
  }


  public Contract contract(String contract) {
    
    this.contract = contract;
    return this;
  }

   /**
   * Get contract
   * @return contract
  **/
  @ApiModelProperty(required = true, value = "")

  public String getContract() {
    return contract;
  }


  public void setContract(String contract) {
    this.contract = contract;
  }


  public Contract payscale(String payscale) {
    
    this.payscale = payscale;
    return this;
  }

   /**
   * Get payscale
   * @return payscale
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPayscale() {
    return payscale;
  }


  public void setPayscale(String payscale) {
    this.payscale = payscale;
  }


  public Contract contractType(String contractType) {
    
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getContractType() {
    return contractType;
  }


  public void setContractType(String contractType) {
    this.contractType = contractType;
  }


  public Contract contractedTime(String contractedTime) {
    
    this.contractedTime = contractedTime;
    return this;
  }

   /**
   * Get contractedTime
   * @return contractedTime
  **/
  @ApiModelProperty(required = true, value = "")

  public String getContractedTime() {
    return contractedTime;
  }


  public void setContractedTime(String contractedTime) {
    this.contractedTime = contractedTime;
  }


  public Contract defaultUnavailabilityHours(String defaultUnavailabilityHours) {
    
    this.defaultUnavailabilityHours = defaultUnavailabilityHours;
    return this;
  }

   /**
   * Get defaultUnavailabilityHours
   * @return defaultUnavailabilityHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultUnavailabilityHours() {
    return defaultUnavailabilityHours;
  }


  public void setDefaultUnavailabilityHours(String defaultUnavailabilityHours) {
    this.defaultUnavailabilityHours = defaultUnavailabilityHours;
  }


  public Contract wtdOptOut(Boolean wtdOptOut) {
    
    this.wtdOptOut = wtdOptOut;
    return this;
  }

   /**
   * Get wtdOptOut
   * @return wtdOptOut
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getWtdOptOut() {
    return wtdOptOut;
  }


  public void setWtdOptOut(Boolean wtdOptOut) {
    this.wtdOptOut = wtdOptOut;
  }


  public Contract salaryFrequency(String salaryFrequency) {
    
    this.salaryFrequency = salaryFrequency;
    return this;
  }

   /**
   * Get salaryFrequency
   * @return salaryFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSalaryFrequency() {
    return salaryFrequency;
  }


  public void setSalaryFrequency(String salaryFrequency) {
    this.salaryFrequency = salaryFrequency;
  }


  public Contract salaryAmount(BigDecimal salaryAmount) {
    
    this.salaryAmount = salaryAmount;
    return this;
  }

   /**
   * Get salaryAmount
   * @return salaryAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSalaryAmount() {
    return salaryAmount;
  }


  public void setSalaryAmount(BigDecimal salaryAmount) {
    this.salaryAmount = salaryAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contract contract = (Contract) o;
    return Objects.equals(this.staffGroup, contract.staffGroup) &&
        Objects.equals(this.grade, contract.grade) &&
        Objects.equals(this.contract, contract.contract) &&
        Objects.equals(this.payscale, contract.payscale) &&
        Objects.equals(this.contractType, contract.contractType) &&
        Objects.equals(this.contractedTime, contract.contractedTime) &&
        Objects.equals(this.defaultUnavailabilityHours, contract.defaultUnavailabilityHours) &&
        Objects.equals(this.wtdOptOut, contract.wtdOptOut) &&
        Objects.equals(this.salaryFrequency, contract.salaryFrequency) &&
        Objects.equals(this.salaryAmount, contract.salaryAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(staffGroup, grade, contract, payscale, contractType, contractedTime, defaultUnavailabilityHours, wtdOptOut, salaryFrequency, salaryAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contract {\n");
    sb.append("    staffGroup: ").append(toIndentedString(staffGroup)).append("\n");
    sb.append("    grade: ").append(toIndentedString(grade)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    payscale: ").append(toIndentedString(payscale)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    contractedTime: ").append(toIndentedString(contractedTime)).append("\n");
    sb.append("    defaultUnavailabilityHours: ").append(toIndentedString(defaultUnavailabilityHours)).append("\n");
    sb.append("    wtdOptOut: ").append(toIndentedString(wtdOptOut)).append("\n");
    sb.append("    salaryFrequency: ").append(toIndentedString(salaryFrequency)).append("\n");
    sb.append("    salaryAmount: ").append(toIndentedString(salaryAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

