/* 
 * DE Provider Direct Engagement API
 *
 * description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing Duty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DutyTests
    {
        // TODO uncomment below to declare an instance variable for Duty
        //private Duty instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Duty
            //instance = new Duty();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Duty
        /// </summary>
        [Test]
        public void DutyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Duty
            //Assert.IsInstanceOf(typeof(Duty), instance);
        }


        /// <summary>
        /// Test the property 'DutyId'
        /// </summary>
        [Test]
        public void DutyIdTest()
        {
            // TODO unit test for the property 'DutyId'
        }
        /// <summary>
        /// Test the property 'SlaveDutyId'
        /// </summary>
        [Test]
        public void SlaveDutyIdTest()
        {
            // TODO unit test for the property 'SlaveDutyId'
        }
        /// <summary>
        /// Test the property 'BlockId'
        /// </summary>
        [Test]
        public void BlockIdTest()
        {
            // TODO unit test for the property 'BlockId'
        }
        /// <summary>
        /// Test the property 'ClientDeptId'
        /// </summary>
        [Test]
        public void ClientDeptIdTest()
        {
            // TODO unit test for the property 'ClientDeptId'
        }
        /// <summary>
        /// Test the property 'SubDiscipline'
        /// </summary>
        [Test]
        public void SubDisciplineTest()
        {
            // TODO unit test for the property 'SubDiscipline'
        }
        /// <summary>
        /// Test the property 'RequestGender'
        /// </summary>
        [Test]
        public void RequestGenderTest()
        {
            // TODO unit test for the property 'RequestGender'
        }
        /// <summary>
        /// Test the property 'Grade'
        /// </summary>
        [Test]
        public void GradeTest()
        {
            // TODO unit test for the property 'Grade'
        }
        /// <summary>
        /// Test the property 'FallbackGrade'
        /// </summary>
        [Test]
        public void FallbackGradeTest()
        {
            // TODO unit test for the property 'FallbackGrade'
        }
        /// <summary>
        /// Test the property 'VacancyReason'
        /// </summary>
        [Test]
        public void VacancyReasonTest()
        {
            // TODO unit test for the property 'VacancyReason'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'EndTime'
        /// </summary>
        [Test]
        public void EndTimeTest()
        {
            // TODO unit test for the property 'EndTime'
        }
        /// <summary>
        /// Test the property 'BreakDuration'
        /// </summary>
        [Test]
        public void BreakDurationTest()
        {
            // TODO unit test for the property 'BreakDuration'
        }
        /// <summary>
        /// Test the property 'PoNumber'
        /// </summary>
        [Test]
        public void PoNumberTest()
        {
            // TODO unit test for the property 'PoNumber'
        }
        /// <summary>
        /// Test the property 'UniqueNumber'
        /// </summary>
        [Test]
        public void UniqueNumberTest()
        {
            // TODO unit test for the property 'UniqueNumber'
        }
        /// <summary>
        /// Test the property 'Agency'
        /// </summary>
        [Test]
        public void AgencyTest()
        {
            // TODO unit test for the property 'Agency'
        }
        /// <summary>
        /// Test the property 'Skill'
        /// </summary>
        [Test]
        public void SkillTest()
        {
            // TODO unit test for the property 'Skill'
        }
        /// <summary>
        /// Test the property 'Specialty'
        /// </summary>
        [Test]
        public void SpecialtyTest()
        {
            // TODO unit test for the property 'Specialty'
        }
        /// <summary>
        /// Test the property 'FallbackSkill'
        /// </summary>
        [Test]
        public void FallbackSkillTest()
        {
            // TODO unit test for the property 'FallbackSkill'
        }
        /// <summary>
        /// Test the property 'FallbackSpeciality'
        /// </summary>
        [Test]
        public void FallbackSpecialityTest()
        {
            // TODO unit test for the property 'FallbackSpeciality'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Rates'
        /// </summary>
        [Test]
        public void RatesTest()
        {
            // TODO unit test for the property 'Rates'
        }
        /// <summary>
        /// Test the property 'TimeIntervalRates'
        /// </summary>
        [Test]
        public void TimeIntervalRatesTest()
        {
            // TODO unit test for the property 'TimeIntervalRates'
        }
        /// <summary>
        /// Test the property 'Person'
        /// </summary>
        [Test]
        public void PersonTest()
        {
            // TODO unit test for the property 'Person'
        }

    }

}
