/* 
 * VMS API
 *
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.VMS.Api;
using ASW.APIServices.VMS.Model;
using ASW.APIServices.VMS.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.VMS.Test
{
    /// <summary>
    ///  Class for testing Agency
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AgencyTests
    {
        // TODO uncomment below to declare an instance variable for Agency
        //private Agency instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Agency
            //instance = new Agency();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Agency
        /// </summary>
        [Test]
        public void AgencyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Agency
            //Assert.IsInstanceOf(typeof(Agency), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ContactTelephone'
        /// </summary>
        [Test]
        public void ContactTelephoneTest()
        {
            // TODO unit test for the property 'ContactTelephone'
        }
        /// <summary>
        /// Test the property 'ContactEmail'
        /// </summary>
        [Test]
        public void ContactEmailTest()
        {
            // TODO unit test for the property 'ContactEmail'
        }

    }

}
