/* 
 * Activity API
 *
 *      ## API for querying worker activity.      This is an early availabilty API, and is subject to change. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing HoursAssignmentEmployeeType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HoursAssignmentEmployeeTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HoursAssignmentEmployeeType
        //private HoursAssignmentEmployeeType instance;

        public HoursAssignmentEmployeeTypeTests()
        {
            // TODO uncomment below to create an instance of HoursAssignmentEmployeeType
            //instance = new HoursAssignmentEmployeeType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HoursAssignmentEmployeeType
        /// </summary>
        [Fact]
        public void HoursAssignmentEmployeeTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HoursAssignmentEmployeeType
            //Assert.IsInstanceOfType<HoursAssignmentEmployeeType> (instance, "variable 'instance' is a HoursAssignmentEmployeeType");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }

    }

}
