/* 
 * Activity API
 *
 *      ## API for querying worker activity.      This is an early availabilty API, and is subject to change. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing HoursAssignmentDuty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HoursAssignmentDutyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HoursAssignmentDuty
        //private HoursAssignmentDuty instance;

        public HoursAssignmentDutyTests()
        {
            // TODO uncomment below to create an instance of HoursAssignmentDuty
            //instance = new HoursAssignmentDuty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HoursAssignmentDuty
        /// </summary>
        [Fact]
        public void HoursAssignmentDutyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HoursAssignmentDuty
            //Assert.IsInstanceOfType<HoursAssignmentDuty> (instance, "variable 'instance' is a HoursAssignmentDuty");
        }


        /// <summary>
        /// Test the property 'When'
        /// </summary>
        [Fact]
        public void WhenTest()
        {
            // TODO unit test for the property 'When'
        }

    }

}
