/* 
 * VMS Provisioning API
 *
 * ## Description  API to be impemented by 247Time (and, potentially, partners) to enable provisioning of accounts and the org structure 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using ASW.APIServices.VMS.Client;
using ASW.APIServices.VMS.Api;
using ASW.APIServices.VMS.Model;

namespace ASW.APIServices.VMS.Test
{
    /// <summary>
    ///  Class for testing ProvisioningApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProvisioningApiTests : IDisposable
    {
        private ProvisioningApi instance;

        public ProvisioningApiTests()
        {
            instance = new ProvisioningApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvisioningApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProvisioningApi
            //Assert.IsType(typeof(ProvisioningApi), instance, "instance is a ProvisioningApi");
        }

        
        /// <summary>
        /// Test ProvisionStructure
        /// </summary>
        [Fact]
        public void ProvisionStructureTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //StructureProvision structureProvision = null;
            //instance.ProvisionStructure(id, structureProvision);
            
        }
        
        /// <summary>
        /// Test ProvisionUser
        /// </summary>
        [Fact]
        public void ProvisionUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //UserProvision userProvision = null;
            //instance.ProvisionUser(id, userProvision);
            
        }
        
    }

}
