/*
 * Workers
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * EmploymentDetails
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T13:36:44.017277Z[Europe/London]")
public class EmploymentDetails {
  public static final String SERIALIZED_NAME_EMPLOYMENT_STATUS = "employmentStatus";
  @SerializedName(SERIALIZED_NAME_EMPLOYMENT_STATUS)
  private String employmentStatus;

  public static final String SERIALIZED_NAME_EMPLOYEE_TYPE = "employeeType";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_TYPE)
  private String employeeType;

  public static final String SERIALIZED_NAME_HIRE_DETAILS = "hireDetails";
  @SerializedName(SERIALIZED_NAME_HIRE_DETAILS)
  private String hireDetails;

  public static final String SERIALIZED_NAME_DATE_JOINED_N_H_S = "dateJoinedNHS";
  @SerializedName(SERIALIZED_NAME_DATE_JOINED_N_H_S)
  private LocalDate dateJoinedNHS;

  public static final String SERIALIZED_NAME_AL_ACCRUAL_PLAN = "alAccrualPlan";
  @SerializedName(SERIALIZED_NAME_AL_ACCRUAL_PLAN)
  private String alAccrualPlan;

  public static final String SERIALIZED_NAME_PREV_EMPLOYER = "prevEmployer";
  @SerializedName(SERIALIZED_NAME_PREV_EMPLOYER)
  private String prevEmployer;

  public static final String SERIALIZED_NAME_AGENCIES = "agencies";
  @SerializedName(SERIALIZED_NAME_AGENCIES)
  private String agencies;


  public EmploymentDetails employmentStatus(String employmentStatus) {
    
    this.employmentStatus = employmentStatus;
    return this;
  }

   /**
   * Get employmentStatus
   * @return employmentStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmploymentStatus() {
    return employmentStatus;
  }


  public void setEmploymentStatus(String employmentStatus) {
    this.employmentStatus = employmentStatus;
  }


  public EmploymentDetails employeeType(String employeeType) {
    
    this.employeeType = employeeType;
    return this;
  }

   /**
   * Get employeeType
   * @return employeeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmployeeType() {
    return employeeType;
  }


  public void setEmployeeType(String employeeType) {
    this.employeeType = employeeType;
  }


  public EmploymentDetails hireDetails(String hireDetails) {
    
    this.hireDetails = hireDetails;
    return this;
  }

   /**
   * Get hireDetails
   * @return hireDetails
  **/
  @ApiModelProperty(required = true, value = "")

  public String getHireDetails() {
    return hireDetails;
  }


  public void setHireDetails(String hireDetails) {
    this.hireDetails = hireDetails;
  }


  public EmploymentDetails dateJoinedNHS(LocalDate dateJoinedNHS) {
    
    this.dateJoinedNHS = dateJoinedNHS;
    return this;
  }

   /**
   * Get dateJoinedNHS
   * @return dateJoinedNHS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getDateJoinedNHS() {
    return dateJoinedNHS;
  }


  public void setDateJoinedNHS(LocalDate dateJoinedNHS) {
    this.dateJoinedNHS = dateJoinedNHS;
  }


  public EmploymentDetails alAccrualPlan(String alAccrualPlan) {
    
    this.alAccrualPlan = alAccrualPlan;
    return this;
  }

   /**
   * Get alAccrualPlan
   * @return alAccrualPlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAlAccrualPlan() {
    return alAccrualPlan;
  }


  public void setAlAccrualPlan(String alAccrualPlan) {
    this.alAccrualPlan = alAccrualPlan;
  }


  public EmploymentDetails prevEmployer(String prevEmployer) {
    
    this.prevEmployer = prevEmployer;
    return this;
  }

   /**
   * Get prevEmployer
   * @return prevEmployer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrevEmployer() {
    return prevEmployer;
  }


  public void setPrevEmployer(String prevEmployer) {
    this.prevEmployer = prevEmployer;
  }


  public EmploymentDetails agencies(String agencies) {
    
    this.agencies = agencies;
    return this;
  }

   /**
   * Get agencies
   * @return agencies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAgencies() {
    return agencies;
  }


  public void setAgencies(String agencies) {
    this.agencies = agencies;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmploymentDetails employmentDetails = (EmploymentDetails) o;
    return Objects.equals(this.employmentStatus, employmentDetails.employmentStatus) &&
        Objects.equals(this.employeeType, employmentDetails.employeeType) &&
        Objects.equals(this.hireDetails, employmentDetails.hireDetails) &&
        Objects.equals(this.dateJoinedNHS, employmentDetails.dateJoinedNHS) &&
        Objects.equals(this.alAccrualPlan, employmentDetails.alAccrualPlan) &&
        Objects.equals(this.prevEmployer, employmentDetails.prevEmployer) &&
        Objects.equals(this.agencies, employmentDetails.agencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employmentStatus, employeeType, hireDetails, dateJoinedNHS, alAccrualPlan, prevEmployer, agencies);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmploymentDetails {\n");
    sb.append("    employmentStatus: ").append(toIndentedString(employmentStatus)).append("\n");
    sb.append("    employeeType: ").append(toIndentedString(employeeType)).append("\n");
    sb.append("    hireDetails: ").append(toIndentedString(hireDetails)).append("\n");
    sb.append("    dateJoinedNHS: ").append(toIndentedString(dateJoinedNHS)).append("\n");
    sb.append("    alAccrualPlan: ").append(toIndentedString(alAccrualPlan)).append("\n");
    sb.append("    prevEmployer: ").append(toIndentedString(prevEmployer)).append("\n");
    sb.append("    agencies: ").append(toIndentedString(agencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

