/*
 * Workers
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.allocate.openapi.model.Identifier;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WorkerPerformanceEventWorker
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T13:36:44.017277Z[Europe/London]")
public class WorkerPerformanceEventWorker {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_IDENTITIES = "identities";
  @SerializedName(SERIALIZED_NAME_IDENTITIES)
  private List<Identifier> identities = null;


  public WorkerPerformanceEventWorker name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Simple name for the worker
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Fred Bloggs", value = "Simple name for the worker")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WorkerPerformanceEventWorker identities(List<Identifier> identities) {
    
    this.identities = identities;
    return this;
  }

  public WorkerPerformanceEventWorker addIdentitiesItem(Identifier identitiesItem) {
    if (this.identities == null) {
      this.identities = new ArrayList<Identifier>();
    }
    this.identities.add(identitiesItem);
    return this;
  }

   /**
   * Collection of identifiers of the worker. There may be several unique identifiers for a worker within HealthSuite, and identifiers used for interactions with 3rd party systems (I.E: their identifiers). 
   * @return identities
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Collection of identifiers of the worker. There may be several unique identifiers for a worker within HealthSuite, and identifiers used for interactions with 3rd party systems (I.E: their identifiers). ")

  public List<Identifier> getIdentities() {
    return identities;
  }


  public void setIdentities(List<Identifier> identities) {
    this.identities = identities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkerPerformanceEventWorker workerPerformanceEventWorker = (WorkerPerformanceEventWorker) o;
    return Objects.equals(this.name, workerPerformanceEventWorker.name) &&
        Objects.equals(this.identities, workerPerformanceEventWorker.identities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, identities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkerPerformanceEventWorker {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    identities: ").append(toIndentedString(identities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

