/* 
 * Worker API and Events
 *
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing Availabilities
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailabilitiesTests
    {
        // TODO uncomment below to declare an instance variable for Availabilities
        //private Availabilities instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Availabilities
            //instance = new Availabilities();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Availabilities
        /// </summary>
        [Test]
        public void AvailabilitiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Availabilities
            //Assert.IsInstanceOf(typeof(Availabilities), instance);
        }


        /// <summary>
        /// Test the property 'Availability'
        /// </summary>
        [Test]
        public void AvailabilityTest()
        {
            // TODO unit test for the property 'Availability'
        }
        /// <summary>
        /// Test the property 'NoBank'
        /// </summary>
        [Test]
        public void NoBankTest()
        {
            // TODO unit test for the property 'NoBank'
        }

    }

}
