/* 
 * Worker API and Events
 *
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing Identification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentificationTests
    {
        // TODO uncomment below to declare an instance variable for Identification
        //private Identification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Identification
            //instance = new Identification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Identification
        /// </summary>
        [Test]
        public void IdentificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Identification
            //Assert.IsInstanceOf(typeof(Identification), instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Forenames'
        /// </summary>
        [Test]
        public void ForenamesTest()
        {
            // TODO unit test for the property 'Forenames'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Test]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'MiddleInitials'
        /// </summary>
        [Test]
        public void MiddleInitialsTest()
        {
            // TODO unit test for the property 'MiddleInitials'
        }
        /// <summary>
        /// Test the property 'KnownAs'
        /// </summary>
        [Test]
        public void KnownAsTest()
        {
            // TODO unit test for the property 'KnownAs'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Test]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }

    }

}
