/* 
 * Worker API and Events
 *
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing Person
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonTests
    {
        // TODO uncomment below to declare an instance variable for Person
        //private Person instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Person
            //instance = new Person();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Person
        /// </summary>
        [Test]
        public void PersonInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Person
            //Assert.IsInstanceOf(typeof(Person), instance);
        }


        /// <summary>
        /// Test the property 'Ids'
        /// </summary>
        [Test]
        public void IdsTest()
        {
            // TODO unit test for the property 'Ids'
        }
        /// <summary>
        /// Test the property 'Identification'
        /// </summary>
        [Test]
        public void IdentificationTest()
        {
            // TODO unit test for the property 'Identification'
        }
        /// <summary>
        /// Test the property 'PersonalInfo'
        /// </summary>
        [Test]
        public void PersonalInfoTest()
        {
            // TODO unit test for the property 'PersonalInfo'
        }
        /// <summary>
        /// Test the property 'EmploymentDetails'
        /// </summary>
        [Test]
        public void EmploymentDetailsTest()
        {
            // TODO unit test for the property 'EmploymentDetails'
        }
        /// <summary>
        /// Test the property 'WorkLocations'
        /// </summary>
        [Test]
        public void WorkLocationsTest()
        {
            // TODO unit test for the property 'WorkLocations'
        }
        /// <summary>
        /// Test the property 'Postings'
        /// </summary>
        [Test]
        public void PostingsTest()
        {
            // TODO unit test for the property 'Postings'
        }
        /// <summary>
        /// Test the property 'Contracts'
        /// </summary>
        [Test]
        public void ContractsTest()
        {
            // TODO unit test for the property 'Contracts'
        }
        /// <summary>
        /// Test the property 'Skills'
        /// </summary>
        [Test]
        public void SkillsTest()
        {
            // TODO unit test for the property 'Skills'
        }
        /// <summary>
        /// Test the property 'Specialties'
        /// </summary>
        [Test]
        public void SpecialtiesTest()
        {
            // TODO unit test for the property 'Specialties'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Test]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Visas'
        /// </summary>
        [Test]
        public void VisasTest()
        {
            // TODO unit test for the property 'Visas'
        }
        /// <summary>
        /// Test the property 'WorkingRestrictions'
        /// </summary>
        [Test]
        public void WorkingRestrictionsTest()
        {
            // TODO unit test for the property 'WorkingRestrictions'
        }
        /// <summary>
        /// Test the property 'Availabilities'
        /// </summary>
        [Test]
        public void AvailabilitiesTest()
        {
            // TODO unit test for the property 'Availabilities'
        }
        /// <summary>
        /// Test the property 'PersonalPattern'
        /// </summary>
        [Test]
        public void PersonalPatternTest()
        {
            // TODO unit test for the property 'PersonalPattern'
        }

    }

}
