/* 
 * Worker API and Events
 *
 *      ## API and events for providing workers. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing WorkingRestrictionDefaultLeaveHours
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkingRestrictionDefaultLeaveHoursTests
    {
        // TODO uncomment below to declare an instance variable for WorkingRestrictionDefaultLeaveHours
        //private WorkingRestrictionDefaultLeaveHours instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkingRestrictionDefaultLeaveHours
            //instance = new WorkingRestrictionDefaultLeaveHours();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkingRestrictionDefaultLeaveHours
        /// </summary>
        [Test]
        public void WorkingRestrictionDefaultLeaveHoursInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WorkingRestrictionDefaultLeaveHours
            //Assert.IsInstanceOf(typeof(WorkingRestrictionDefaultLeaveHours), instance);
        }


        /// <summary>
        /// Test the property 'UseWorkingDay'
        /// </summary>
        [Test]
        public void UseWorkingDayTest()
        {
            // TODO unit test for the property 'UseWorkingDay'
        }
        /// <summary>
        /// Test the property 'MondayTime'
        /// </summary>
        [Test]
        public void MondayTimeTest()
        {
            // TODO unit test for the property 'MondayTime'
        }
        /// <summary>
        /// Test the property 'TuesdayTime'
        /// </summary>
        [Test]
        public void TuesdayTimeTest()
        {
            // TODO unit test for the property 'TuesdayTime'
        }
        /// <summary>
        /// Test the property 'WednesdayTime'
        /// </summary>
        [Test]
        public void WednesdayTimeTest()
        {
            // TODO unit test for the property 'WednesdayTime'
        }
        /// <summary>
        /// Test the property 'FridayTime'
        /// </summary>
        [Test]
        public void FridayTimeTest()
        {
            // TODO unit test for the property 'FridayTime'
        }
        /// <summary>
        /// Test the property 'SaturdayTime'
        /// </summary>
        [Test]
        public void SaturdayTimeTest()
        {
            // TODO unit test for the property 'SaturdayTime'
        }
        /// <summary>
        /// Test the property 'SundayTime'
        /// </summary>
        [Test]
        public void SundayTimeTest()
        {
            // TODO unit test for the property 'SundayTime'
        }

    }

}
