# coding: utf-8

"""
    Vacancy Booking API and Events

         ## Duty Booking API and events and Events   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api_server
from api_server.models.vacancy_published_event import VacancyPublishedEvent  # noqa: E501
from api_server.rest import ApiException


class TestVacancyPublishedEvent(unittest.TestCase):
    """VacancyPublishedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacancyPublishedEvent(self):
        """Test VacancyPublishedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api_server.models.vacancy_published_event.VacancyPublishedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
