/*
 * Workers
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Contract
 */
public class ContractTest {
    private final Contract model = new Contract();

    /**
     * Model tests for Contract
     */
    @Test
    public void testContract() {
        // TODO: test Contract
    }

    /**
     * Test the property 'staffGroup'
     */
    @Test
    public void staffGroupTest() {
        // TODO: test staffGroup
    }

    /**
     * Test the property 'grade'
     */
    @Test
    public void gradeTest() {
        // TODO: test grade
    }

    /**
     * Test the property 'contract'
     */
    @Test
    public void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'payscale'
     */
    @Test
    public void payscaleTest() {
        // TODO: test payscale
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'contractedTime'
     */
    @Test
    public void contractedTimeTest() {
        // TODO: test contractedTime
    }

    /**
     * Test the property 'defaultUnavailabilityHours'
     */
    @Test
    public void defaultUnavailabilityHoursTest() {
        // TODO: test defaultUnavailabilityHours
    }

    /**
     * Test the property 'wtdOptOut'
     */
    @Test
    public void wtdOptOutTest() {
        // TODO: test wtdOptOut
    }

    /**
     * Test the property 'salaryFrequency'
     */
    @Test
    public void salaryFrequencyTest() {
        // TODO: test salaryFrequency
    }

    /**
     * Test the property 'salaryAmount'
     */
    @Test
    public void salaryAmountTest() {
        // TODO: test salaryAmount
    }

}
