/*
 * Workers
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.allocate.openapi.model.Attribute;
import com.allocate.openapi.model.Availabilities;
import com.allocate.openapi.model.Contract;
import com.allocate.openapi.model.EmploymentDetails;
import com.allocate.openapi.model.Identification;
import com.allocate.openapi.model.PersonalInfo;
import com.allocate.openapi.model.PersonalPattern;
import com.allocate.openapi.model.Posting;
import com.allocate.openapi.model.Skill;
import com.allocate.openapi.model.Specialty;
import com.allocate.openapi.model.Visa;
import com.allocate.openapi.model.WorkLocations;
import com.allocate.openapi.model.WorkingRestriction;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Person
 */
public class PersonTest {
    private final Person model = new Person();

    /**
     * Model tests for Person
     */
    @Test
    public void testPerson() {
        // TODO: test Person
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'personalInfo'
     */
    @Test
    public void personalInfoTest() {
        // TODO: test personalInfo
    }

    /**
     * Test the property 'employmentDetails'
     */
    @Test
    public void employmentDetailsTest() {
        // TODO: test employmentDetails
    }

    /**
     * Test the property 'workLocations'
     */
    @Test
    public void workLocationsTest() {
        // TODO: test workLocations
    }

    /**
     * Test the property 'postings'
     */
    @Test
    public void postingsTest() {
        // TODO: test postings
    }

    /**
     * Test the property 'contracts'
     */
    @Test
    public void contractsTest() {
        // TODO: test contracts
    }

    /**
     * Test the property 'skills'
     */
    @Test
    public void skillsTest() {
        // TODO: test skills
    }

    /**
     * Test the property 'specialties'
     */
    @Test
    public void specialtiesTest() {
        // TODO: test specialties
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'visas'
     */
    @Test
    public void visasTest() {
        // TODO: test visas
    }

    /**
     * Test the property 'workingRestrictions'
     */
    @Test
    public void workingRestrictionsTest() {
        // TODO: test workingRestrictions
    }

    /**
     * Test the property 'availabilities'
     */
    @Test
    public void availabilitiesTest() {
        // TODO: test availabilities
    }

    /**
     * Test the property 'personalPattern'
     */
    @Test
    public void personalPatternTest() {
        // TODO: test personalPattern
    }

}
