# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_server.models.base_model_ import Model
from api_server import util


class DutyTempStaffingNoteDeletedEventAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, duty_id=None, note_id=None):  # noqa: E501
        """DutyTempStaffingNoteDeletedEventAllOf - a model defined in OpenAPI

        :param duty_id: The duty_id of this DutyTempStaffingNoteDeletedEventAllOf.  # noqa: E501
        :type duty_id: str
        :param note_id: The note_id of this DutyTempStaffingNoteDeletedEventAllOf.  # noqa: E501
        :type note_id: str
        """
        self.openapi_types = {
            'duty_id': str,
            'note_id': str
        }

        self.attribute_map = {
            'duty_id': 'dutyId',
            'note_id': 'noteId'
        }

        self._duty_id = duty_id
        self._note_id = note_id

    @classmethod
    def from_dict(cls, dikt) -> 'DutyTempStaffingNoteDeletedEventAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DutyTempStaffingNoteDeletedEvent_allOf of this DutyTempStaffingNoteDeletedEventAllOf.  # noqa: E501
        :rtype: DutyTempStaffingNoteDeletedEventAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def duty_id(self):
        """Gets the duty_id of this DutyTempStaffingNoteDeletedEventAllOf.


        :return: The duty_id of this DutyTempStaffingNoteDeletedEventAllOf.
        :rtype: str
        """
        return self._duty_id

    @duty_id.setter
    def duty_id(self, duty_id):
        """Sets the duty_id of this DutyTempStaffingNoteDeletedEventAllOf.


        :param duty_id: The duty_id of this DutyTempStaffingNoteDeletedEventAllOf.
        :type duty_id: str
        """

        self._duty_id = duty_id

    @property
    def note_id(self):
        """Gets the note_id of this DutyTempStaffingNoteDeletedEventAllOf.

        Identifier for the note  # noqa: E501

        :return: The note_id of this DutyTempStaffingNoteDeletedEventAllOf.
        :rtype: str
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id):
        """Sets the note_id of this DutyTempStaffingNoteDeletedEventAllOf.

        Identifier for the note  # noqa: E501

        :param note_id: The note_id of this DutyTempStaffingNoteDeletedEventAllOf.
        :type note_id: str
        """

        self._note_id = note_id
