/* 
 * Duties and Events
 *
 * ## Duties and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing DutyDetailsWhere
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DutyDetailsWhereTests
    {
        // TODO uncomment below to declare an instance variable for DutyDetailsWhere
        //private DutyDetailsWhere instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DutyDetailsWhere
            //instance = new DutyDetailsWhere();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DutyDetailsWhere
        /// </summary>
        [Test]
        public void DutyDetailsWhereInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" DutyDetailsWhere
            //Assert.IsInstanceOf(typeof(DutyDetailsWhere), instance);
        }


        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Test]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

    }

}
