/*
 * DE Provider Direct Engagement API
 *
 * description
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

type BookingInfo struct {

	// Id of the contract in DE Provider system
	ContractId string `json:"contractId,omitempty"`

	// Id of the booked agency
	Agency int32 `json:"agency,omitempty"`

	Person Person `json:"person,omitempty"`

	// Booking grade trust identifier.
	Grade string `json:"grade,omitempty"`

	// Trust Pay Agency & Trust Pays DE provider - split rate between pay to worker and pay to agency
	Rates []Rates `json:"rates,omitempty"`
}
