/*
 * Workers
 *
 * ## Workers and events 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

import (
	"errors"
)

// AnnualLeaveClaimsApiService is a service that implents the logic for the AnnualLeaveClaimsApiServicer
// This service should implement the business logic for every endpoint for the AnnualLeaveClaimsApi API. 
// Include any external packages or services that will be required by this service.
type AnnualLeaveClaimsApiService struct {
}

// NewAnnualLeaveClaimsApiService creates a default api service
func NewAnnualLeaveClaimsApiService() AnnualLeaveClaimsApiServicer {
	return &AnnualLeaveClaimsApiService{}
}

// SubmitAnnualLeaveClaim - 
func (s *AnnualLeaveClaimsApiService) SubmitAnnualLeaveClaim(id string, leaveClaim LeaveClaim) (interface{}, error) {
	// TODO - update SubmitAnnualLeaveClaim with the required logic for this service method.
	// Add api_annual_leave_claims_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SubmitAnnualLeaveClaim' not implemented")
}
