/* 
 * Duties and Events
 *
 * ## Duties and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ASW.APIServices.Core.Api;
using ASW.APIServices.Core.Model;
using ASW.APIServices.Core.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ASW.APIServices.Core.Test
{
    /// <summary>
    ///  Class for testing DutyDeletedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DutyDeletedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DutyDeletedEvent
        //private DutyDeletedEvent instance;

        public DutyDeletedEventTests()
        {
            // TODO uncomment below to create an instance of DutyDeletedEvent
            //instance = new DutyDeletedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DutyDeletedEvent
        /// </summary>
        [Fact]
        public void DutyDeletedEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DutyDeletedEvent
            //Assert.IsInstanceOfType<DutyDeletedEvent> (instance, "variable 'instance' is a DutyDeletedEvent");
        }


        /// <summary>
        /// Test the property 'DutyId'
        /// </summary>
        [Fact]
        public void DutyIdTest()
        {
            // TODO unit test for the property 'DutyId'
        }

    }

}
