/*
 * Duties and Events
 *
 * ## Duties and Events 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

// DutyTempStaffingExpressionOfInterestEvent - A note previously added to a duty has been deleted.
type DutyTempStaffingExpressionOfInterestEvent struct {

	EventType string `json:"eventType"`

	Id string `json:"id,omitempty"`

	DutyId string `json:"dutyId,omitempty"`

	// Identifier for the note
	WorkerId string `json:"workerId,omitempty"`
}
