/*
 * VMS API
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.vms.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DutyRequirements
 */
public class DutyRequirementsTest {
    private final DutyRequirements model = new DutyRequirements();

    /**
     * Model tests for DutyRequirements
     */
    @Test
    public void testDutyRequirements() {
        // TODO: test DutyRequirements
    }

    /**
     * Test the property 'skill'
     */
    @Test
    public void skillTest() {
        // TODO: test skill
    }

    /**
     * Test the property 'specialty'
     */
    @Test
    public void specialtyTest() {
        // TODO: test specialty
    }

    /**
     * Test the property 'fallbackSkill'
     */
    @Test
    public void fallbackSkillTest() {
        // TODO: test fallbackSkill
    }

    /**
     * Test the property 'fallbackSpeciality'
     */
    @Test
    public void fallbackSpecialityTest() {
        // TODO: test fallbackSpeciality
    }

}
