/*
 * Duties and Events
 * ## Duties and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DutyRequirementsGradeRequirement
 */
public class DutyRequirementsGradeRequirementTest {
    private final DutyRequirementsGradeRequirement model = new DutyRequirementsGradeRequirement();

    /**
     * Model tests for DutyRequirementsGradeRequirement
     */
    @Test
    public void testDutyRequirementsGradeRequirement() {
        // TODO: test DutyRequirementsGradeRequirement
    }

    /**
     * Test the property 'grade'
     */
    @Test
    public void gradeTest() {
        // TODO: test grade
    }

    /**
     * Test the property 'gradeType'
     */
    @Test
    public void gradeTypeTest() {
        // TODO: test gradeType
    }

    /**
     * Test the property 'gradeTypeCategory'
     */
    @Test
    public void gradeTypeCategoryTest() {
        // TODO: test gradeTypeCategory
    }

}
