/*
 * Duties and Events
 * ## Duties and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.allocate.openapi.model.DutyEventAllOf;
import com.allocate.openapi.model.Event;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DutyCancelledEvent
 */
public class DutyCancelledEventTest {
    private final DutyCancelledEvent model = new DutyCancelledEvent();

    /**
     * Model tests for DutyCancelledEvent
     */
    @Test
    public void testDutyCancelledEvent() {
        // TODO: test DutyCancelledEvent
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'dutyId'
     */
    @Test
    public void dutyIdTest() {
        // TODO: test dutyId
    }

}
