/*
 * Duties and Events
 * ## Duties and Events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.allocate.openapi.model.Duty;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DutyAssignmentRedeploymentEventAllOf
 */
public class DutyAssignmentRedeploymentEventAllOfTest {
    private final DutyAssignmentRedeploymentEventAllOf model = new DutyAssignmentRedeploymentEventAllOf();

    /**
     * Model tests for DutyAssignmentRedeploymentEventAllOf
     */
    @Test
    public void testDutyAssignmentRedeploymentEventAllOf() {
        // TODO: test DutyAssignmentRedeploymentEventAllOf
    }

    /**
     * Test the property 'assignmentNumber'
     */
    @Test
    public void assignmentNumberTest() {
        // TODO: test assignmentNumber
    }

    /**
     * Test the property 'originalDuty'
     */
    @Test
    public void originalDutyTest() {
        // TODO: test originalDuty
    }

    /**
     * Test the property 'newDuty'
     */
    @Test
    public void newDutyTest() {
        // TODO: test newDuty
    }

}
