# coding: utf-8

"""
    Workers

    ## Workers and events   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api_server
from api_server.models.contact_details_updated_event import ContactDetailsUpdatedEvent  # noqa: E501
from api_server.rest import ApiException


class TestContactDetailsUpdatedEvent(unittest.TestCase):
    """ContactDetailsUpdatedEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactDetailsUpdatedEvent(self):
        """Test ContactDetailsUpdatedEvent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api_server.models.contact_details_updated_event.ContactDetailsUpdatedEvent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
