# coding: utf-8

"""
    Workers

    ## Workers and events   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api_server
from api_server.models.working_restriction_hours_of_work import WorkingRestrictionHoursOfWork  # noqa: E501
from api_server.rest import ApiException


class TestWorkingRestrictionHoursOfWork(unittest.TestCase):
    """WorkingRestrictionHoursOfWork unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkingRestrictionHoursOfWork(self):
        """Test WorkingRestrictionHoursOfWork"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api_server.models.working_restriction_hours_of_work.WorkingRestrictionHoursOfWork()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
