/*
 * DE Provider Direct Engagement API
 *
 * description
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

type InlineObject struct {

	StartTime string `json:"startTime,omitempty"`

	EndTime string `json:"endTime,omitempty"`

	// Break Duration
	Break int32 `json:"break,omitempty"`

	// Status of the timesheet
	Status string `json:"status,omitempty"`

	// Trust Pay Agency & Trust Pays DE provider - split rate between pay to worker and pay to agency
	Rates []Rates `json:"rates,omitempty"`
}
