/*
 * DE Provider Direct Engagement API
 *
 * description
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	allocateApi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	DutyApiService := allocateApi.NewDutyApiService()
	DutyApiController := allocateApi.NewDutyApiController(DutyApiService)

	EventApiService := allocateApi.NewEventApiService()
	EventApiController := allocateApi.NewEventApiController(EventApiService)

	ReferenceDataApiService := allocateApi.NewReferenceDataApiService()
	ReferenceDataApiController := allocateApi.NewReferenceDataApiController(ReferenceDataApiService)

	router := allocateApi.NewRouter(DutyApiController, EventApiController, ReferenceDataApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
