/*
 * VMS Provisioning API
 * ## Description  API to be impemented by 247Time (and, potentially, partners) to enable provisioning of accounts and the org structure 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.vms.api;

import com.allocate.vms.ApiException;
import com.allocate.vms.api.model.StructureProvision;
import com.allocate.vms.api.model.UserProvision;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProvisioningApi
 */
@Ignore
public class ProvisioningApiTest {

    private final ProvisioningApi api = new ProvisioningApi();

    
    /**
     * 
     *
     * Provision the supplied structure.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void provisionStructureTest() throws ApiException {
        String id = null;
        StructureProvision structureProvision = null;
        api.provisionStructure(id, structureProvision);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Provision the supplied user.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void provisionUserTest() throws ApiException {
        String id = null;
        UserProvision userProvision = null;
        api.provisionUser(id, userProvision);

        // TODO: test validations
    }
    
}
