/* 
 * Activity API
 *
 *      ## API for querying worker activity.      This is an early availabilty API, and is subject to change. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@allocatesoftware.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ASW.APIServices.Core.Client.OpenAPIDateConverter;

namespace ASW.APIServices.Core.Model
{
    /// <summary>
    /// HoursAssignmentPosting
    /// </summary>
    [DataContract]
    public partial class HoursAssignmentPosting :  IEquatable<HoursAssignmentPosting>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HoursAssignmentPosting" /> class.
        /// </summary>
        /// <param name="assignmentNumber">assignmentNumber.</param>
        public HoursAssignmentPosting(string assignmentNumber = default(string))
        {
            this.AssignmentNumber = assignmentNumber;
        }
        
        /// <summary>
        /// Gets or Sets AssignmentNumber
        /// </summary>
        [DataMember(Name="assignmentNumber", EmitDefaultValue=false)]
        public string AssignmentNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HoursAssignmentPosting {\n");
            sb.Append("  AssignmentNumber: ").Append(AssignmentNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HoursAssignmentPosting);
        }

        /// <summary>
        /// Returns true if HoursAssignmentPosting instances are equal
        /// </summary>
        /// <param name="input">Instance of HoursAssignmentPosting to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HoursAssignmentPosting input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssignmentNumber == input.AssignmentNumber ||
                    (this.AssignmentNumber != null &&
                    this.AssignmentNumber.Equals(input.AssignmentNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssignmentNumber != null)
                    hashCode = hashCode * 59 + this.AssignmentNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
