# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api_server.models.base_model_ import Model
from api_server import util


class HoursAssignmentCostCentre(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, name=None, description=None):  # noqa: E501
        """HoursAssignmentCostCentre - a model defined in OpenAPI

        :param code: The code of this HoursAssignmentCostCentre.  # noqa: E501
        :type code: str
        :param name: The name of this HoursAssignmentCostCentre.  # noqa: E501
        :type name: str
        :param description: The description of this HoursAssignmentCostCentre.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'code': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'code': 'code',
            'name': 'name',
            'description': 'description'
        }

        self._code = code
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'HoursAssignmentCostCentre':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HoursAssignment_costCentre of this HoursAssignmentCostCentre.  # noqa: E501
        :rtype: HoursAssignmentCostCentre
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this HoursAssignmentCostCentre.


        :return: The code of this HoursAssignmentCostCentre.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this HoursAssignmentCostCentre.


        :param code: The code of this HoursAssignmentCostCentre.
        :type code: str
        """

        self._code = code

    @property
    def name(self):
        """Gets the name of this HoursAssignmentCostCentre.


        :return: The name of this HoursAssignmentCostCentre.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HoursAssignmentCostCentre.


        :param name: The name of this HoursAssignmentCostCentre.
        :type name: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this HoursAssignmentCostCentre.


        :return: The description of this HoursAssignmentCostCentre.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this HoursAssignmentCostCentre.


        :param description: The description of this HoursAssignmentCostCentre.
        :type description: str
        """

        self._description = description
