/**
 * Workers
 * ## Workers and events 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Identifier } from './identifier';
import { ContactLogInformationDetails } from './contactLogInformationDetails';


export interface ContactLogInformation { 
    type: ContactLogInformation.TypeEnum;
    when?: Date;
    who?: { [key: string]: Identifier; };
    details?: ContactLogInformationDetails;
}
export namespace ContactLogInformation {
    export type TypeEnum = 'telephone' | 'email' | 'IM' | 'faceToFace';
    export const TypeEnum = {
        Telephone: 'telephone' as TypeEnum,
        Email: 'email' as TypeEnum,
        IM: 'IM' as TypeEnum,
        FaceToFace: 'faceToFace' as TypeEnum
    };
}


