/*
 * Activity API
 *      ## API for querying worker activity.      This is an early availabilty API, and is subject to change. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@allocatesoftware.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.allocate.openapi.model.DateSpan;
import com.allocate.openapi.model.HoursAssignmentAssignment;
import com.allocate.openapi.model.HoursAssignmentCancellation;
import com.allocate.openapi.model.HoursAssignmentCostCentre;
import com.allocate.openapi.model.HoursAssignmentDuty;
import com.allocate.openapi.model.HoursAssignmentEmployeeType;
import com.allocate.openapi.model.HoursAssignmentFulfillment;
import com.allocate.openapi.model.HoursAssignmentLocation;
import com.allocate.openapi.model.HoursAssignmentOwningUnit;
import com.allocate.openapi.model.HoursAssignmentPerson;
import com.allocate.openapi.model.HoursAssignmentPost;
import com.allocate.openapi.model.HoursAssignmentPosting;
import com.allocate.openapi.model.HoursAssignmentRequirement;
import com.allocate.openapi.model.HoursAssignmentShift;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * HoursAssignment
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-09T13:33:21.258826Z[Europe/London]")
public class HoursAssignment {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_WHEN = "when";
  @SerializedName(SERIALIZED_NAME_WHEN)
  private LocalDate when;

  public static final String SERIALIZED_NAME_ACTUAL = "actual";
  @SerializedName(SERIALIZED_NAME_ACTUAL)
  private DateSpan actual;

  public static final String SERIALIZED_NAME_WORK_TIME = "workTime";
  @SerializedName(SERIALIZED_NAME_WORK_TIME)
  private Integer workTime;

  public static final String SERIALIZED_NAME_CONTRACTED_TIME = "contractedTime";
  @SerializedName(SERIALIZED_NAME_CONTRACTED_TIME)
  private Integer contractedTime;

  /**
   * Details where the duty is in it’s lifecycle. *   Requested &#x3D; (Requested Bank Duty) *   Accepted &#x3D; (Roster Approved) *   Approved &#x3D; (Finalised) *   Submitted &#x3D; (PAID) *   Paid *   Unlocked &#x3D; (Was once Finalised state.) *   Relocked &#x3D; (Finalised given that it was once un-finalised for some reason) 
   */
  @JsonAdapter(PayStateEnum.Adapter.class)
  public enum PayStateEnum {
    REQUESTED("requested"),
    
    ACCEPTED("accepted"),
    
    APPROVED("approved"),
    
    SUBMITTED("submitted"),
    
    PAID("paid"),
    
    UNLOCKED("unlocked"),
    
    RELOCKED("relocked");

    private String value;

    PayStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PayStateEnum fromValue(String value) {
      for (PayStateEnum b : PayStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PayStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PayStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PayStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PayStateEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PAY_STATE = "payState";
  @SerializedName(SERIALIZED_NAME_PAY_STATE)
  private PayStateEnum payState;

  public static final String SERIALIZED_NAME_EMPLOYEE_TYPE = "employeeType";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_TYPE)
  private HoursAssignmentEmployeeType employeeType;

  public static final String SERIALIZED_NAME_PERSON = "person";
  @SerializedName(SERIALIZED_NAME_PERSON)
  private HoursAssignmentPerson person;

  public static final String SERIALIZED_NAME_ASSIGNMENT = "assignment";
  @SerializedName(SERIALIZED_NAME_ASSIGNMENT)
  private HoursAssignmentAssignment assignment;

  public static final String SERIALIZED_NAME_POST = "post";
  @SerializedName(SERIALIZED_NAME_POST)
  private HoursAssignmentPost post;

  public static final String SERIALIZED_NAME_POSTING = "posting";
  @SerializedName(SERIALIZED_NAME_POSTING)
  private HoursAssignmentPosting posting;

  public static final String SERIALIZED_NAME_CANCELLATION = "cancellation";
  @SerializedName(SERIALIZED_NAME_CANCELLATION)
  private HoursAssignmentCancellation cancellation;

  public static final String SERIALIZED_NAME_IN_CHARGE = "inCharge";
  @SerializedName(SERIALIZED_NAME_IN_CHARGE)
  private Boolean inCharge;

  public static final String SERIALIZED_NAME_SHIFT = "shift";
  @SerializedName(SERIALIZED_NAME_SHIFT)
  private HoursAssignmentShift shift;

  public static final String SERIALIZED_NAME_DUTY = "duty";
  @SerializedName(SERIALIZED_NAME_DUTY)
  private HoursAssignmentDuty duty;

  public static final String SERIALIZED_NAME_FULFILLMENT = "fulfillment";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT)
  private HoursAssignmentFulfillment fulfillment;

  public static final String SERIALIZED_NAME_COST_CENTRE = "costCentre";
  @SerializedName(SERIALIZED_NAME_COST_CENTRE)
  private HoursAssignmentCostCentre costCentre;

  public static final String SERIALIZED_NAME_OWNING_UNIT = "owningUnit";
  @SerializedName(SERIALIZED_NAME_OWNING_UNIT)
  private HoursAssignmentOwningUnit owningUnit;

  public static final String SERIALIZED_NAME_RESOURCING_UNIT = "resourcingUnit";
  @SerializedName(SERIALIZED_NAME_RESOURCING_UNIT)
  private HoursAssignmentOwningUnit resourcingUnit;

  public static final String SERIALIZED_NAME_REQUIREMENT = "requirement";
  @SerializedName(SERIALIZED_NAME_REQUIREMENT)
  private HoursAssignmentRequirement requirement;

  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private HoursAssignmentLocation location;

  public static final String SERIALIZED_NAME_ADDITIONAL_DUTY_REASON = "additionalDutyReason";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DUTY_REASON)
  private String additionalDutyReason;

  public static final String SERIALIZED_NAME_DUTY_HAS_WARNINGS = "dutyHasWarnings";
  @SerializedName(SERIALIZED_NAME_DUTY_HAS_WARNINGS)
  private Boolean dutyHasWarnings;


  public HoursAssignment id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Identifier for the hours assignment
   * @return id
  **/
  @ApiModelProperty(example = "123523", required = true, value = "Identifier for the hours assignment")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public HoursAssignment when(LocalDate when) {
    
    this.when = when;
    return this;
  }

   /**
   * Date assignment begins on
   * @return when
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date assignment begins on")

  public LocalDate getWhen() {
    return when;
  }


  public void setWhen(LocalDate when) {
    this.when = when;
  }


  public HoursAssignment actual(DateSpan actual) {
    
    this.actual = actual;
    return this;
  }

   /**
   * Get actual
   * @return actual
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateSpan getActual() {
    return actual;
  }


  public void setActual(DateSpan actual) {
    this.actual = actual;
  }


  public HoursAssignment workTime(Integer workTime) {
    
    this.workTime = workTime;
    return this;
  }

   /**
   * Number of minutes worked in assignment
   * @return workTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "450", value = "Number of minutes worked in assignment")

  public Integer getWorkTime() {
    return workTime;
  }


  public void setWorkTime(Integer workTime) {
    this.workTime = workTime;
  }


  public HoursAssignment contractedTime(Integer contractedTime) {
    
    this.contractedTime = contractedTime;
    return this;
  }

   /**
   * Number of minutes that count towards the person’s contracted hours
   * @return contractedTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "450", value = "Number of minutes that count towards the person’s contracted hours")

  public Integer getContractedTime() {
    return contractedTime;
  }


  public void setContractedTime(Integer contractedTime) {
    this.contractedTime = contractedTime;
  }


  public HoursAssignment payState(PayStateEnum payState) {
    
    this.payState = payState;
    return this;
  }

   /**
   * Details where the duty is in it’s lifecycle. *   Requested &#x3D; (Requested Bank Duty) *   Accepted &#x3D; (Roster Approved) *   Approved &#x3D; (Finalised) *   Submitted &#x3D; (PAID) *   Paid *   Unlocked &#x3D; (Was once Finalised state.) *   Relocked &#x3D; (Finalised given that it was once un-finalised for some reason) 
   * @return payState
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details where the duty is in it’s lifecycle. *   Requested = (Requested Bank Duty) *   Accepted = (Roster Approved) *   Approved = (Finalised) *   Submitted = (PAID) *   Paid *   Unlocked = (Was once Finalised state.) *   Relocked = (Finalised given that it was once un-finalised for some reason) ")

  public PayStateEnum getPayState() {
    return payState;
  }


  public void setPayState(PayStateEnum payState) {
    this.payState = payState;
  }


  public HoursAssignment employeeType(HoursAssignmentEmployeeType employeeType) {
    
    this.employeeType = employeeType;
    return this;
  }

   /**
   * Get employeeType
   * @return employeeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentEmployeeType getEmployeeType() {
    return employeeType;
  }


  public void setEmployeeType(HoursAssignmentEmployeeType employeeType) {
    this.employeeType = employeeType;
  }


  public HoursAssignment person(HoursAssignmentPerson person) {
    
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentPerson getPerson() {
    return person;
  }


  public void setPerson(HoursAssignmentPerson person) {
    this.person = person;
  }


  public HoursAssignment assignment(HoursAssignmentAssignment assignment) {
    
    this.assignment = assignment;
    return this;
  }

   /**
   * Get assignment
   * @return assignment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentAssignment getAssignment() {
    return assignment;
  }


  public void setAssignment(HoursAssignmentAssignment assignment) {
    this.assignment = assignment;
  }


  public HoursAssignment post(HoursAssignmentPost post) {
    
    this.post = post;
    return this;
  }

   /**
   * Get post
   * @return post
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentPost getPost() {
    return post;
  }


  public void setPost(HoursAssignmentPost post) {
    this.post = post;
  }


  public HoursAssignment posting(HoursAssignmentPosting posting) {
    
    this.posting = posting;
    return this;
  }

   /**
   * Get posting
   * @return posting
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentPosting getPosting() {
    return posting;
  }


  public void setPosting(HoursAssignmentPosting posting) {
    this.posting = posting;
  }


  public HoursAssignment cancellation(HoursAssignmentCancellation cancellation) {
    
    this.cancellation = cancellation;
    return this;
  }

   /**
   * Get cancellation
   * @return cancellation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentCancellation getCancellation() {
    return cancellation;
  }


  public void setCancellation(HoursAssignmentCancellation cancellation) {
    this.cancellation = cancellation;
  }


  public HoursAssignment inCharge(Boolean inCharge) {
    
    this.inCharge = inCharge;
    return this;
  }

   /**
   * Was the employee in charge?
   * @return inCharge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Was the employee in charge?")

  public Boolean getInCharge() {
    return inCharge;
  }


  public void setInCharge(Boolean inCharge) {
    this.inCharge = inCharge;
  }


  public HoursAssignment shift(HoursAssignmentShift shift) {
    
    this.shift = shift;
    return this;
  }

   /**
   * Get shift
   * @return shift
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentShift getShift() {
    return shift;
  }


  public void setShift(HoursAssignmentShift shift) {
    this.shift = shift;
  }


  public HoursAssignment duty(HoursAssignmentDuty duty) {
    
    this.duty = duty;
    return this;
  }

   /**
   * Get duty
   * @return duty
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentDuty getDuty() {
    return duty;
  }


  public void setDuty(HoursAssignmentDuty duty) {
    this.duty = duty;
  }


  public HoursAssignment fulfillment(HoursAssignmentFulfillment fulfillment) {
    
    this.fulfillment = fulfillment;
    return this;
  }

   /**
   * Get fulfillment
   * @return fulfillment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentFulfillment getFulfillment() {
    return fulfillment;
  }


  public void setFulfillment(HoursAssignmentFulfillment fulfillment) {
    this.fulfillment = fulfillment;
  }


  public HoursAssignment costCentre(HoursAssignmentCostCentre costCentre) {
    
    this.costCentre = costCentre;
    return this;
  }

   /**
   * Get costCentre
   * @return costCentre
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentCostCentre getCostCentre() {
    return costCentre;
  }


  public void setCostCentre(HoursAssignmentCostCentre costCentre) {
    this.costCentre = costCentre;
  }


  public HoursAssignment owningUnit(HoursAssignmentOwningUnit owningUnit) {
    
    this.owningUnit = owningUnit;
    return this;
  }

   /**
   * Get owningUnit
   * @return owningUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentOwningUnit getOwningUnit() {
    return owningUnit;
  }


  public void setOwningUnit(HoursAssignmentOwningUnit owningUnit) {
    this.owningUnit = owningUnit;
  }


  public HoursAssignment resourcingUnit(HoursAssignmentOwningUnit resourcingUnit) {
    
    this.resourcingUnit = resourcingUnit;
    return this;
  }

   /**
   * Get resourcingUnit
   * @return resourcingUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentOwningUnit getResourcingUnit() {
    return resourcingUnit;
  }


  public void setResourcingUnit(HoursAssignmentOwningUnit resourcingUnit) {
    this.resourcingUnit = resourcingUnit;
  }


  public HoursAssignment requirement(HoursAssignmentRequirement requirement) {
    
    this.requirement = requirement;
    return this;
  }

   /**
   * Get requirement
   * @return requirement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentRequirement getRequirement() {
    return requirement;
  }


  public void setRequirement(HoursAssignmentRequirement requirement) {
    this.requirement = requirement;
  }


  public HoursAssignment location(HoursAssignmentLocation location) {
    
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HoursAssignmentLocation getLocation() {
    return location;
  }


  public void setLocation(HoursAssignmentLocation location) {
    this.location = location;
  }


  public HoursAssignment additionalDutyReason(String additionalDutyReason) {
    
    this.additionalDutyReason = additionalDutyReason;
    return this;
  }

   /**
   * Get additionalDutyReason
   * @return additionalDutyReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAdditionalDutyReason() {
    return additionalDutyReason;
  }


  public void setAdditionalDutyReason(String additionalDutyReason) {
    this.additionalDutyReason = additionalDutyReason;
  }


  public HoursAssignment dutyHasWarnings(Boolean dutyHasWarnings) {
    
    this.dutyHasWarnings = dutyHasWarnings;
    return this;
  }

   /**
   * Get dutyHasWarnings
   * @return dutyHasWarnings
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getDutyHasWarnings() {
    return dutyHasWarnings;
  }


  public void setDutyHasWarnings(Boolean dutyHasWarnings) {
    this.dutyHasWarnings = dutyHasWarnings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HoursAssignment hoursAssignment = (HoursAssignment) o;
    return Objects.equals(this.id, hoursAssignment.id) &&
        Objects.equals(this.when, hoursAssignment.when) &&
        Objects.equals(this.actual, hoursAssignment.actual) &&
        Objects.equals(this.workTime, hoursAssignment.workTime) &&
        Objects.equals(this.contractedTime, hoursAssignment.contractedTime) &&
        Objects.equals(this.payState, hoursAssignment.payState) &&
        Objects.equals(this.employeeType, hoursAssignment.employeeType) &&
        Objects.equals(this.person, hoursAssignment.person) &&
        Objects.equals(this.assignment, hoursAssignment.assignment) &&
        Objects.equals(this.post, hoursAssignment.post) &&
        Objects.equals(this.posting, hoursAssignment.posting) &&
        Objects.equals(this.cancellation, hoursAssignment.cancellation) &&
        Objects.equals(this.inCharge, hoursAssignment.inCharge) &&
        Objects.equals(this.shift, hoursAssignment.shift) &&
        Objects.equals(this.duty, hoursAssignment.duty) &&
        Objects.equals(this.fulfillment, hoursAssignment.fulfillment) &&
        Objects.equals(this.costCentre, hoursAssignment.costCentre) &&
        Objects.equals(this.owningUnit, hoursAssignment.owningUnit) &&
        Objects.equals(this.resourcingUnit, hoursAssignment.resourcingUnit) &&
        Objects.equals(this.requirement, hoursAssignment.requirement) &&
        Objects.equals(this.location, hoursAssignment.location) &&
        Objects.equals(this.additionalDutyReason, hoursAssignment.additionalDutyReason) &&
        Objects.equals(this.dutyHasWarnings, hoursAssignment.dutyHasWarnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, when, actual, workTime, contractedTime, payState, employeeType, person, assignment, post, posting, cancellation, inCharge, shift, duty, fulfillment, costCentre, owningUnit, resourcingUnit, requirement, location, additionalDutyReason, dutyHasWarnings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HoursAssignment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    when: ").append(toIndentedString(when)).append("\n");
    sb.append("    actual: ").append(toIndentedString(actual)).append("\n");
    sb.append("    workTime: ").append(toIndentedString(workTime)).append("\n");
    sb.append("    contractedTime: ").append(toIndentedString(contractedTime)).append("\n");
    sb.append("    payState: ").append(toIndentedString(payState)).append("\n");
    sb.append("    employeeType: ").append(toIndentedString(employeeType)).append("\n");
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    assignment: ").append(toIndentedString(assignment)).append("\n");
    sb.append("    post: ").append(toIndentedString(post)).append("\n");
    sb.append("    posting: ").append(toIndentedString(posting)).append("\n");
    sb.append("    cancellation: ").append(toIndentedString(cancellation)).append("\n");
    sb.append("    inCharge: ").append(toIndentedString(inCharge)).append("\n");
    sb.append("    shift: ").append(toIndentedString(shift)).append("\n");
    sb.append("    duty: ").append(toIndentedString(duty)).append("\n");
    sb.append("    fulfillment: ").append(toIndentedString(fulfillment)).append("\n");
    sb.append("    costCentre: ").append(toIndentedString(costCentre)).append("\n");
    sb.append("    owningUnit: ").append(toIndentedString(owningUnit)).append("\n");
    sb.append("    resourcingUnit: ").append(toIndentedString(resourcingUnit)).append("\n");
    sb.append("    requirement: ").append(toIndentedString(requirement)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    additionalDutyReason: ").append(toIndentedString(additionalDutyReason)).append("\n");
    sb.append("    dutyHasWarnings: ").append(toIndentedString(dutyHasWarnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

