/*
 * DE Provider Direct Engagement API
 * description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.allocate.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BookingResponse
 */
public class BookingResponseTest {
    private final BookingResponse model = new BookingResponse();

    /**
     * Model tests for BookingResponse
     */
    @Test
    public void testBookingResponse() {
        // TODO: test BookingResponse
    }

    /**
     * Test the property 'dutyId'
     */
    @Test
    public void dutyIdTest() {
        // TODO: test dutyId
    }

    /**
     * Test the property 'bookingId'
     */
    @Test
    public void bookingIdTest() {
        // TODO: test bookingId
    }

    /**
     * Test the property 'allocatePersonId'
     */
    @Test
    public void allocatePersonIdTest() {
        // TODO: test allocatePersonId
    }

    /**
     * Test the property 'masterDutyId'
     */
    @Test
    public void masterDutyIdTest() {
        // TODO: test masterDutyId
    }

    /**
     * Test the property 'slaveDutyId'
     */
    @Test
    public void slaveDutyIdTest() {
        // TODO: test slaveDutyId
    }

}
