# coding: utf-8

"""
    VMS Provisioning API

    ## Description  API to be impemented by 247Time (and, potentially, partners) to enable provisioning of accounts and the org structure   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@allocatesoftware.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from api_server.configuration import Configuration


class UserProvisionItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'unit_id': 'str',
        'roles': 'list[str]'
    }

    attribute_map = {
        'unit_id': 'unitId',
        'roles': 'roles'
    }

    def __init__(self, unit_id=None, roles=None, local_vars_configuration=None):  # noqa: E501
        """UserProvisionItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._unit_id = None
        self._roles = None
        self.discriminator = None

        if unit_id is not None:
            self.unit_id = unit_id
        if roles is not None:
            self.roles = roles

    @property
    def unit_id(self):
        """Gets the unit_id of this UserProvisionItem.  # noqa: E501

        Identifier of the unit within the HealthSuite ecosystem  # noqa: E501

        :return: The unit_id of this UserProvisionItem.  # noqa: E501
        :rtype: str
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this UserProvisionItem.

        Identifier of the unit within the HealthSuite ecosystem  # noqa: E501

        :param unit_id: The unit_id of this UserProvisionItem.  # noqa: E501
        :type: str
        """

        self._unit_id = unit_id

    @property
    def roles(self):
        """Gets the roles of this UserProvisionItem.  # noqa: E501

        Optional list of textual roles that the user has in relation to the unit  # noqa: E501

        :return: The roles of this UserProvisionItem.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this UserProvisionItem.

        Optional list of textual roles that the user has in relation to the unit  # noqa: E501

        :param roles: The roles of this UserProvisionItem.  # noqa: E501
        :type: list[str]
        """

        self._roles = roles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserProvisionItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserProvisionItem):
            return True

        return self.to_dict() != other.to_dict()
