# coding: utf-8

"""
    DE Provider Direct Engagement API

    description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import api_server
from api_server.models.reference_data_response import ReferenceDataResponse  # noqa: E501
from api_server.rest import ApiException


class TestReferenceDataResponse(unittest.TestCase):
    """ReferenceDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReferenceDataResponse(self):
        """Test ReferenceDataResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = api_server.models.reference_data_response.ReferenceDataResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
