# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from api_server.models.base_model_ import Model
from api_server import util


class DateSpan(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, _from: date=None, to: date=None):
        """DateSpan - a model defined in OpenAPI

        :param _from: The _from of this DateSpan.
        :param to: The to of this DateSpan.
        """
        self.openapi_types = {
            '_from': date,
            'to': date
        }

        self.attribute_map = {
            '_from': 'from',
            'to': 'to'
        }

        self.__from = _from
        self._to = to

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DateSpan':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DateSpan of this DateSpan.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _from(self):
        """Gets the _from of this DateSpan.

        When the span starts

        :return: The _from of this DateSpan.
        :rtype: date
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this DateSpan.

        When the span starts

        :param _from: The _from of this DateSpan.
        :type _from: date
        """

        self.__from = _from

    @property
    def to(self):
        """Gets the to of this DateSpan.

        When the span ends

        :return: The to of this DateSpan.
        :rtype: date
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this DateSpan.

        When the span ends

        :param to: The to of this DateSpan.
        :type to: date
        """

        self._to = to
