# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from api_server.models.base_model_ import Model
from api_server import util


class WorkerRegistrationResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, person_id: str=None):
        """WorkerRegistrationResponse - a model defined in OpenAPI

        :param person_id: The person_id of this WorkerRegistrationResponse.
        """
        self.openapi_types = {
            'person_id': str
        }

        self.attribute_map = {
            'person_id': 'personId'
        }

        self._person_id = person_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'WorkerRegistrationResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The WorkerRegistrationResponse of this WorkerRegistrationResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def person_id(self):
        """Gets the person_id of this WorkerRegistrationResponse.

        ASWid of the person

        :return: The person_id of this WorkerRegistrationResponse.
        :rtype: str
        """
        return self._person_id

    @person_id.setter
    def person_id(self, person_id):
        """Sets the person_id of this WorkerRegistrationResponse.

        ASWid of the person

        :param person_id: The person_id of this WorkerRegistrationResponse.
        :type person_id: str
        """
        if person_id is None:
            raise ValueError("Invalid value for `person_id`, must not be `None`")

        self._person_id = person_id
