/*
 * VMS API
 *
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

type DutyLocation struct {

	Id string `json:"id"`

	Name string `json:"name"`

	ParentLocation DutyLocation `json:"parentLocation,omitempty"`
}
