/*
 * VMS API
 *
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AcceptAgencyOffer - 
func AcceptAgencyOffer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CancelBooking - 
func CancelBooking(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// CancelBookingRequest - 
func CancelBookingRequest(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetBooking - 
func GetBooking(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
