/*
 * VMS API
 *
 * ## Description  API to be impemented by VMS systems for integration into HealthSuite business processes 
 *
 * API version: 1.0.0
 * Contact: support@allocatesoftware.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package allocateApi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetCostings - 
func GetCostings(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SendDutyToAgencies - 
func SendDutyToAgencies(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SendDutyToAgency - 
func SendDutyToAgency(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
